# 1. aşama: React build
FROM node:20-alpine AS build

WORKDIR /app

# Paket dosyalarını kopyala ve bağımlılıkları kur
COPY package*.json ./
RUN npm install

# Geri kalan her şeyi kopyala ve production build al
COPY . .
RUN npm run build

# 2. aşama: Nginx ile statik dosyaları serve et
FROM nginx:alpine

# Build edilen dosyaları nginx'in root'una kopyala
COPY --from=build /app/dist /usr/share/nginx/html

# Dışarıya açacağımız port
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]